// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAppointment = `-- name: CancelAppointment :one
UPDATE appointments
SET status = 'cancelled', cancellation_reason = $2, updated_at = now()
WHERE id = $1
RETURNING id, patient_id, doctor_id, schedule_id, start_time, end_time, status, notes, cancellation_reason, created_by, created_at, updated_at
`

type CancelAppointmentParams struct {
	ID                 uuid.UUID   `json:"id"`
	CancellationReason pgtype.Text `json:"cancellation_reason"`
}

func (q *Queries) CancelAppointment(ctx context.Context, arg CancelAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, cancelAppointment, arg.ID, arg.CancellationReason)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ScheduleID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkAppointmentConflict = `-- name: CheckAppointmentConflict :one
SELECT EXISTS (
    SELECT 1 FROM appointments
    WHERE doctor_id = $1
      AND status IN ('scheduled', 'confirmed')
      AND tstzrange(start_time, end_time) && tstzrange($2, $3)
      AND id != COALESCE($4, '00000000-0000-0000-0000-000000000000'::uuid)
) AS conflict_exists
`

type CheckAppointmentConflictParams struct {
	DoctorID    uuid.UUID   `json:"doctor_id"`
	Tstzrange   interface{} `json:"tstzrange"`
	Tstzrange_2 interface{} `json:"tstzrange_2"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) CheckAppointmentConflict(ctx context.Context, arg CheckAppointmentConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAppointmentConflict,
		arg.DoctorID,
		arg.Tstzrange,
		arg.Tstzrange_2,
		arg.ID,
	)
	var conflict_exists bool
	err := row.Scan(&conflict_exists)
	return conflict_exists, err
}

const countAppointmentsByDoctorInRange = `-- name: CountAppointmentsByDoctorInRange :one
SELECT COUNT(*) FROM appointments
WHERE doctor_id = $1
  AND start_time >= $2
  AND end_time <= $3
  AND status IN ('scheduled', 'confirmed')
`

type CountAppointmentsByDoctorInRangeParams struct {
	DoctorID  uuid.UUID `json:"doctor_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) CountAppointmentsByDoctorInRange(ctx context.Context, arg CountAppointmentsByDoctorInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointmentsByDoctorInRange, arg.DoctorID, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
    patient_id, doctor_id, schedule_id, start_time, end_time, status, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, patient_id, doctor_id, schedule_id, start_time, end_time, status, notes, cancellation_reason, created_by, created_at, updated_at
`

type CreateAppointmentParams struct {
	PatientID  uuid.UUID   `json:"patient_id"`
	DoctorID   uuid.UUID   `json:"doctor_id"`
	ScheduleID pgtype.UUID `json:"schedule_id"`
	StartTime  time.Time   `json:"start_time"`
	EndTime    time.Time   `json:"end_time"`
	Status     string      `json:"status"`
	Notes      pgtype.Text `json:"notes"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.PatientID,
		arg.DoctorID,
		arg.ScheduleID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ScheduleID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointment = `-- name: GetAppointment :one
SELECT id, patient_id, doctor_id, schedule_id, start_time, end_time, status, notes, cancellation_reason, created_by, created_at, updated_at
FROM appointments
WHERE id = $1
`

func (q *Queries) GetAppointment(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ScheduleID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointmentsByDoctor = `-- name: ListAppointmentsByDoctor :many
SELECT id, patient_id, doctor_id, schedule_id, start_time, end_time, status, notes, cancellation_reason, created_by, created_at, updated_at
FROM appointments
WHERE doctor_id = $1
  AND start_time >= $2
  AND end_time <= $3
  AND status IN ('scheduled', 'confirmed')
ORDER BY start_time ASC
`

type ListAppointmentsByDoctorParams struct {
	DoctorID  uuid.UUID `json:"doctor_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) ListAppointmentsByDoctor(ctx context.Context, arg ListAppointmentsByDoctorParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByDoctor, arg.DoctorID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ScheduleID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CancellationReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByPatient = `-- name: ListAppointmentsByPatient :many
SELECT id, patient_id, doctor_id, schedule_id, start_time, end_time, status, notes, cancellation_reason, created_by, created_at, updated_at
FROM appointments
WHERE patient_id = $1
ORDER BY start_time DESC
`

func (q *Queries) ListAppointmentsByPatient(ctx context.Context, patientID uuid.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ScheduleID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CancellationReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleAppointment = `-- name: RescheduleAppointment :one
UPDATE appointments
SET start_time = $2, end_time = $3, updated_at = now()
WHERE id = $1
RETURNING id, patient_id, doctor_id, schedule_id, start_time, end_time, status, notes, cancellation_reason, created_by, created_at, updated_at
`

type RescheduleAppointmentParams struct {
	ID        uuid.UUID `json:"id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) RescheduleAppointment(ctx context.Context, arg RescheduleAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, rescheduleAppointment, arg.ID, arg.StartTime, arg.EndTime)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ScheduleID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, patient_id, doctor_id, schedule_id, start_time, end_time, status, notes, cancellation_reason, created_by, created_at, updated_at
`

type UpdateAppointmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentStatus, arg.ID, arg.Status)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ScheduleID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
