// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countAppointments = `-- name: CountAppointments :one
SELECT count(*) FROM appointments
WHERE ($1::uuid IS NULL OR patient_id = $1)
  AND ($2::uuid IS NULL OR doctor_id = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL OR end_time > $4)
  AND ($5::timestamptz IS NULL OR start_time < $5)
`

type CountAppointmentsParams struct {
	PatientID *uuid.UUID
	DoctorID  *uuid.UUID
	Status    *string
	FromTime  *time.Time
	ToTime    *time.Time
}

func (q *Queries) CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointments,
		arg.PatientID,
		arg.DoctorID,
		arg.Status,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (patient_id, doctor_id, start_time, end_time, status, notes, created_by)
VALUES ($1, $2, $3, $4, 'scheduled', $5, $6)
RETURNING id, patient_id, doctor_id, start_time, end_time, status, notes, cancellation_reason, version, created_by, created_at, updated_at
`

type CreateAppointmentParams struct {
	PatientID uuid.UUID
	DoctorID  uuid.UUID
	StartTime time.Time
	EndTime   time.Time
	Notes     *string
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.PatientID,
		arg.DoctorID,
		arg.StartTime,
		arg.EndTime,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, patient_id, doctor_id, start_time, end_time, status, notes, cancellation_reason, version, created_by, created_at, updated_at FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotentResponse = `-- name: GetIdempotentResponse :one
SELECT user_id, request_hash, response_status, response_body FROM idempotency_keys
WHERE key = $1 AND endpoint = $2 AND expires_at > now()
`

type GetIdempotentResponseParams struct {
	Key      string
	Endpoint string
}

type GetIdempotentResponseRow struct {
	UserID         *uuid.UUID
	RequestHash    string
	ResponseStatus int32
	ResponseBody   *json.RawMessage
}

func (q *Queries) GetIdempotentResponse(ctx context.Context, arg GetIdempotentResponseParams) (GetIdempotentResponseRow, error) {
	row := q.db.QueryRow(ctx, getIdempotentResponse, arg.Key, arg.Endpoint)
	var i GetIdempotentResponseRow
	err := row.Scan(
		&i.UserID,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
	)
	return i, err
}

const getNotificationByMsgID = `-- name: GetNotificationByMsgID :one
SELECT id, appointment_id, channel, recipient, subject, body, status, attempts, last_error, nats_msg_id, created_at, updated_at FROM notifications WHERE nats_msg_id = $1
`

func (q *Queries) GetNotificationByMsgID(ctx context.Context, natsMsgID *string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByMsgID, natsMsgID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NatsMsgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_user_id, action, entity_type, entity_id, details)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	ActorUserID *uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Details     json.RawMessage
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
	)
	return err
}

const insertIdempotentResponse = `-- name: InsertIdempotentResponse :one
INSERT INTO idempotency_keys (key, endpoint, user_id, request_hash, response_status, response_body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, now() + make_interval(secs => $7::int))
ON CONFLICT (key, endpoint) DO UPDATE SET key = EXCLUDED.key WHERE false
RETURNING key
`

type InsertIdempotentResponseParams struct {
	Key            string
	Endpoint       string
	UserID         *uuid.UUID
	RequestHash    string
	ResponseStatus int32
	ResponseBody   *json.RawMessage
	TtlSeconds     int32
}

// DO UPDATE ... WHERE false + RETURNING: concurrent inserts of the same key
// serialize; the loser gets the winner's row back instead of silently
// committing a duplicate booking.
func (q *Queries) InsertIdempotentResponse(ctx context.Context, arg InsertIdempotentResponseParams) (string, error) {
	row := q.db.QueryRow(ctx, insertIdempotentResponse,
		arg.Key,
		arg.Endpoint,
		arg.UserID,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.TtlSeconds,
	)
	var key string
	err := row.Scan(&key)
	return key, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (id, appointment_id, channel, recipient, subject, body, nats_msg_id)
VALUES ($1::uuid, $2, $3::varchar, $4::varchar, $5::text, $6::text, $7::text)
ON CONFLICT (nats_msg_id) DO NOTHING
RETURNING id, appointment_id, channel, recipient, subject, body, status, attempts, last_error, nats_msg_id, created_at, updated_at
`

type InsertNotificationParams struct {
	ID            uuid.UUID
	AppointmentID *uuid.UUID
	Channel       string
	Recipient     string
	Subject       string
	Body          string
	MsgID         string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ID,
		arg.AppointmentID,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.MsgID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NatsMsgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAppointmentsForDoctorInRange = `-- name: ListActiveAppointmentsForDoctorInRange :many
SELECT id, patient_id, doctor_id, start_time, end_time, status, notes, cancellation_reason, version, created_by, created_at, updated_at FROM appointments
WHERE doctor_id = $1 AND status IN ('scheduled', 'confirmed')
  AND tstzrange(start_time, end_time) && tstzrange($2::timestamptz, $3::timestamptz)
`

type ListActiveAppointmentsForDoctorInRangeParams struct {
	DoctorID   uuid.UUID
	RangeStart time.Time
	RangeEnd   time.Time
}

func (q *Queries) ListActiveAppointmentsForDoctorInRange(ctx context.Context, arg ListActiveAppointmentsForDoctorInRangeParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listActiveAppointmentsForDoctorInRange, arg.DoctorID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CancellationReason,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, patient_id, doctor_id, start_time, end_time, status, notes, cancellation_reason, version, created_by, created_at, updated_at FROM appointments
WHERE ($3::uuid IS NULL OR patient_id = $3)
  AND ($4::uuid IS NULL OR doctor_id = $4)
  AND ($5::text IS NULL OR status = $5)
  AND ($6::timestamptz IS NULL OR end_time > $6)
  AND ($7::timestamptz IS NULL OR start_time < $7)
ORDER BY start_time DESC
LIMIT $1 OFFSET $2
`

type ListAppointmentsParams struct {
	Limit     int32
	Offset    int32
	PatientID *uuid.UUID
	DoctorID  *uuid.UUID
	Status    *string
	FromTime  *time.Time
	ToTime    *time.Time
}

func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments,
		arg.Limit,
		arg.Offset,
		arg.PatientID,
		arg.DoctorID,
		arg.Status,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CancellationReason,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDead = `-- name: MarkNotificationDead :exec
UPDATE notifications SET status = 'dead_letter', attempts = attempts + 1, last_error = $2 WHERE id = $1
`

type MarkNotificationDeadParams struct {
	ID        uuid.UUID
	LastError *string
}

func (q *Queries) MarkNotificationDead(ctx context.Context, arg MarkNotificationDeadParams) error {
	_, err := q.db.Exec(ctx, markNotificationDead, arg.ID, arg.LastError)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications SET status = 'failed', attempts = attempts + 1, last_error = $2 WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID        uuid.UUID
	LastError *string
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.LastError)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications SET status = 'sent' WHERE id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const rescheduleAppointment = `-- name: RescheduleAppointment :one
UPDATE appointments SET start_time = $2, end_time = $3, version = version + 1
WHERE id = $1 AND status IN ('scheduled', 'confirmed')
RETURNING id, patient_id, doctor_id, start_time, end_time, status, notes, cancellation_reason, version, created_by, created_at, updated_at
`

type RescheduleAppointmentParams struct {
	ID        uuid.UUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) RescheduleAppointment(ctx context.Context, arg RescheduleAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, rescheduleAppointment, arg.ID, arg.StartTime, arg.EndTime)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionAppointmentStatus = `-- name: TransitionAppointmentStatus :one
UPDATE appointments SET status = $2,
    cancellation_reason = COALESCE($3, cancellation_reason),
    version = version + 1
WHERE id = $1 AND status = $4
RETURNING id, patient_id, doctor_id, start_time, end_time, status, notes, cancellation_reason, version, created_by, created_at, updated_at
`

type TransitionAppointmentStatusParams struct {
	ID                 uuid.UUID
	Status             string
	CancellationReason *string
	ExpectedStatus     string
}

func (q *Queries) TransitionAppointmentStatus(ctx context.Context, arg TransitionAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, transitionAppointmentStatus,
		arg.ID,
		arg.Status,
		arg.CancellationReason,
		arg.ExpectedStatus,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CancellationReason,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
