// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAppointments = `-- name: CountAppointments :one
SELECT COUNT(*) FROM appointments
WHERE (profile_id = $1 OR doctor_profile_id = $1)
  AND status = ANY($2)
`

type CountAppointmentsParams struct {
	ProfileID uuid.UUID
	Status    string
}

func (q *Queries) CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointments, arg.ProfileID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one

INSERT INTO appointments (
    profile_id, doctor_profile_id, appointment_type_id,
    scheduled_start, scheduled_end, status,
    visit_notes, follow_up_date, cancellation_reason,
    version, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, profile_id, doctor_profile_id, appointment_type_id,
    scheduled_start, scheduled_end, status,
    visit_notes, follow_up_date, cancellation_reason,
    version, created_by, created_at, updated_at
`

type CreateAppointmentParams struct {
	ProfileID          uuid.UUID
	DoctorProfileID    uuid.UUID
	AppointmentTypeID  uuid.UUID
	ScheduledStart     time.Time
	ScheduledEnd       time.Time
	Status             string
	VisitNotes         pgtype.Text
	FollowUpDate       *time.Time
	CancellationReason pgtype.Text
	Version            int32
	CreatedBy          *uuid.UUID
}

// Appointments (schema v2: profile-based, typed, queue-ready)
func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ProfileID,
		arg.DoctorProfileID,
		arg.AppointmentTypeID,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.Status,
		arg.VisitNotes,
		arg.FollowUpDate,
		arg.CancellationReason,
		arg.Version,
		arg.CreatedBy,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.DoctorProfileID,
		&i.AppointmentTypeID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Status,
		&i.VisitNotes,
		&i.FollowUpDate,
		&i.CancellationReason,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, profile_id, doctor_profile_id, appointment_type_id,
    scheduled_start, scheduled_end, status,
    visit_notes, follow_up_date, cancellation_reason,
    version, created_by, created_at, updated_at
FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.DoctorProfileID,
		&i.AppointmentTypeID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Status,
		&i.VisitNotes,
		&i.FollowUpDate,
		&i.CancellationReason,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, profile_id, doctor_profile_id, appointment_type_id,
    scheduled_start, scheduled_end, status,
    visit_notes, follow_up_date, cancellation_reason,
    version, created_by, created_at, updated_at
FROM appointments
WHERE (profile_id = $1 OR doctor_profile_id = $1)
  AND status = ANY($2)
ORDER BY scheduled_start DESC
LIMIT $3 OFFSET $4
`

type ListAppointmentsParams struct {
	ProfileID uuid.UUID
	Status    string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments,
		arg.ProfileID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.DoctorProfileID,
			&i.AppointmentTypeID,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.Status,
			&i.VisitNotes,
			&i.FollowUpDate,
			&i.CancellationReason,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleAppointment = `-- name: RescheduleAppointment :one
UPDATE appointments SET
    scheduled_start = $2,
    scheduled_end   = $3,
    version         = version + 1
WHERE id = $1
RETURNING id, profile_id, doctor_profile_id, appointment_type_id,
    scheduled_start, scheduled_end, status,
    visit_notes, follow_up_date, cancellation_reason,
    version, created_by, created_at, updated_at
`

type RescheduleAppointmentParams struct {
	ID             uuid.UUID
	ScheduledStart time.Time
	ScheduledEnd   time.Time
}

func (q *Queries) RescheduleAppointment(ctx context.Context, arg RescheduleAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, rescheduleAppointment, arg.ID, arg.ScheduledStart, arg.ScheduledEnd)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.DoctorProfileID,
		&i.AppointmentTypeID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Status,
		&i.VisitNotes,
		&i.FollowUpDate,
		&i.CancellationReason,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionAppointmentStatus = `-- name: TransitionAppointmentStatus :one
UPDATE appointments SET
    status = $2,
    cancellation_reason = $3,
    version = version + 1
WHERE id = $1 AND status = $4
RETURNING id, profile_id, doctor_profile_id, appointment_type_id,
    scheduled_start, scheduled_end, status,
    visit_notes, follow_up_date, cancellation_reason,
    version, created_by, created_at, updated_at
`

type TransitionAppointmentStatusParams struct {
	ID                 uuid.UUID
	Status             string
	CancellationReason pgtype.Text
	Status_2           string
}

func (q *Queries) TransitionAppointmentStatus(ctx context.Context, arg TransitionAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, transitionAppointmentStatus,
		arg.ID,
		arg.Status,
		arg.CancellationReason,
		arg.Status_2,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.DoctorProfileID,
		&i.AppointmentTypeID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Status,
		&i.VisitNotes,
		&i.FollowUpDate,
		&i.CancellationReason,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
