// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctor.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDoctor = `-- name: CreateDoctor :one
INSERT INTO doctors (
    user_id, specialization, license_number, bio
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, specialization, license_number, bio, is_active, created_at, updated_at
`

type CreateDoctorParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	Specialization pgtype.Text `json:"specialization"`
	LicenseNumber  pgtype.Text `json:"license_number"`
	Bio            pgtype.Text `json:"bio"`
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, createDoctor,
		arg.UserID,
		arg.Specialization,
		arg.LicenseNumber,
		arg.Bio,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.LicenseNumber,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDoctorSchedule = `-- name: CreateDoctorSchedule :one
INSERT INTO doctor_schedules (doctor_id, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, doctor_id, day_of_week, start_time, end_time, is_active, created_at, updated_at
`

type CreateDoctorScheduleParams struct {
	DoctorID  uuid.UUID   `json:"doctor_id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateDoctorSchedule(ctx context.Context, arg CreateDoctorScheduleParams) (DoctorSchedule, error) {
	row := q.db.QueryRow(ctx, createDoctorSchedule,
		arg.DoctorID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i DoctorSchedule
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDoctorScheduleException = `-- name: CreateDoctorScheduleException :one
INSERT INTO doctor_schedule_exceptions (doctor_id, exception_date, start_time, end_time, is_unavailable, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, doctor_id, exception_date, start_time, end_time, is_unavailable, reason, created_at
`

type CreateDoctorScheduleExceptionParams struct {
	DoctorID      uuid.UUID   `json:"doctor_id"`
	ExceptionDate pgtype.Date `json:"exception_date"`
	StartTime     pgtype.Time `json:"start_time"`
	EndTime       pgtype.Time `json:"end_time"`
	IsUnavailable bool        `json:"is_unavailable"`
	Reason        pgtype.Text `json:"reason"`
}

func (q *Queries) CreateDoctorScheduleException(ctx context.Context, arg CreateDoctorScheduleExceptionParams) (DoctorScheduleException, error) {
	row := q.db.QueryRow(ctx, createDoctorScheduleException,
		arg.DoctorID,
		arg.ExceptionDate,
		arg.StartTime,
		arg.EndTime,
		arg.IsUnavailable,
		arg.Reason,
	)
	var i DoctorScheduleException
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.ExceptionDate,
		&i.StartTime,
		&i.EndTime,
		&i.IsUnavailable,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDoctor = `-- name: DeleteDoctor :exec
DELETE FROM doctors WHERE id = $1
`

func (q *Queries) DeleteDoctor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDoctor, id)
	return err
}

const deleteDoctorSchedule = `-- name: DeleteDoctorSchedule :exec
DELETE FROM doctor_schedules WHERE id = $1
`

func (q *Queries) DeleteDoctorSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDoctorSchedule, id)
	return err
}

const getDoctor = `-- name: GetDoctor :one
SELECT id, user_id, specialization, license_number, bio, is_active, created_at, updated_at
FROM doctors
WHERE id = $1
`

func (q *Queries) GetDoctor(ctx context.Context, id uuid.UUID) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctor, id)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.LicenseNumber,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctorByUserID = `-- name: GetDoctorByUserID :one
SELECT id, user_id, specialization, license_number, bio, is_active, created_at, updated_at
FROM doctors
WHERE user_id = $1
`

func (q *Queries) GetDoctorByUserID(ctx context.Context, userID uuid.UUID) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctorByUserID, userID)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.LicenseNumber,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctorSchedule = `-- name: GetDoctorSchedule :many
SELECT id, doctor_id, day_of_week, start_time, end_time, is_active, created_at, updated_at
FROM doctor_schedules
WHERE doctor_id = $1 AND is_active = true
ORDER BY day_of_week, start_time
`

func (q *Queries) GetDoctorSchedule(ctx context.Context, doctorID uuid.UUID) ([]DoctorSchedule, error) {
	rows, err := q.db.Query(ctx, getDoctorSchedule, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoctorSchedule{}
	for rows.Next() {
		var i DoctorSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDoctorScheduleExceptions = `-- name: GetDoctorScheduleExceptions :many
SELECT id, doctor_id, exception_date, start_time, end_time, is_unavailable, reason, created_at
FROM doctor_schedule_exceptions
WHERE doctor_id = $1
ORDER BY exception_date
`

func (q *Queries) GetDoctorScheduleExceptions(ctx context.Context, doctorID uuid.UUID) ([]DoctorScheduleException, error) {
	rows, err := q.db.Query(ctx, getDoctorScheduleExceptions, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoctorScheduleException{}
	for rows.Next() {
		var i DoctorScheduleException
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.ExceptionDate,
			&i.StartTime,
			&i.EndTime,
			&i.IsUnavailable,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctors = `-- name: ListDoctors :many
SELECT id, user_id, specialization, license_number, bio, is_active, created_at, updated_at
FROM doctors
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListDoctors(ctx context.Context) ([]Doctor, error) {
	rows, err := q.db.Query(ctx, listDoctors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Doctor{}
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Specialization,
			&i.LicenseNumber,
			&i.Bio,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoctor = `-- name: UpdateDoctor :one
UPDATE doctors
SET specialization = $2, license_number = $3, bio = $4, is_active = $5, updated_at = now()
WHERE id = $1
RETURNING id, user_id, specialization, license_number, bio, is_active, created_at, updated_at
`

type UpdateDoctorParams struct {
	ID             uuid.UUID   `json:"id"`
	Specialization pgtype.Text `json:"specialization"`
	LicenseNumber  pgtype.Text `json:"license_number"`
	Bio            pgtype.Text `json:"bio"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, updateDoctor,
		arg.ID,
		arg.Specialization,
		arg.LicenseNumber,
		arg.Bio,
		arg.IsActive,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.LicenseNumber,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
