// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctors.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDoctor = `-- name: CreateDoctor :one
INSERT INTO doctors (user_id, specialization, license_number, bio)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, specialization, license_number, bio, is_active, created_at, updated_at
`

type CreateDoctorParams struct {
	UserID         uuid.UUID
	Specialization string
	LicenseNumber  string
	Bio            *string
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, createDoctor,
		arg.UserID,
		arg.Specialization,
		arg.LicenseNumber,
		arg.Bio,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.LicenseNumber,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDoctorSchedule = `-- name: CreateDoctorSchedule :one
INSERT INTO doctor_schedules (doctor_id, day_of_week, start_time, end_time, slot_minutes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, doctor_id, day_of_week, start_time, end_time, slot_minutes, is_active, created_at, updated_at
`

type CreateDoctorScheduleParams struct {
	DoctorID    uuid.UUID
	DayOfWeek   int16
	StartTime   pgtype.Time
	EndTime     pgtype.Time
	SlotMinutes int32
}

func (q *Queries) CreateDoctorSchedule(ctx context.Context, arg CreateDoctorScheduleParams) (DoctorSchedule, error) {
	row := q.db.QueryRow(ctx, createDoctorSchedule,
		arg.DoctorID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.SlotMinutes,
	)
	var i DoctorSchedule
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.SlotMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduleException = `-- name: CreateScheduleException :one
INSERT INTO doctor_schedule_exceptions (doctor_id, exception_date, is_unavailable, start_time, end_time, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, doctor_id, exception_date, is_unavailable, start_time, end_time, reason, created_at, updated_at
`

type CreateScheduleExceptionParams struct {
	DoctorID      uuid.UUID
	ExceptionDate time.Time
	IsUnavailable bool
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	Reason        *string
}

func (q *Queries) CreateScheduleException(ctx context.Context, arg CreateScheduleExceptionParams) (DoctorScheduleException, error) {
	row := q.db.QueryRow(ctx, createScheduleException,
		arg.DoctorID,
		arg.ExceptionDate,
		arg.IsUnavailable,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	var i DoctorScheduleException
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.ExceptionDate,
		&i.IsUnavailable,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDoctorSchedule = `-- name: DeactivateDoctorSchedule :exec
UPDATE doctor_schedules SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateDoctorSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateDoctorSchedule, id)
	return err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT d.id, d.user_id, d.specialization, d.license_number, d.bio, d.is_active, d.created_at, d.updated_at, u.full_name, u.email AS user_email FROM doctors d
JOIN users u ON u.id = d.user_id
WHERE d.id = $1
`

type GetDoctorByIDRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Specialization string
	LicenseNumber  string
	Bio            *string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	FullName       string
	UserEmail      string
}

func (q *Queries) GetDoctorByID(ctx context.Context, id uuid.UUID) (GetDoctorByIDRow, error) {
	row := q.db.QueryRow(ctx, getDoctorByID, id)
	var i GetDoctorByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.LicenseNumber,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.UserEmail,
	)
	return i, err
}

const listDoctorSchedules = `-- name: ListDoctorSchedules :many
SELECT id, doctor_id, day_of_week, start_time, end_time, slot_minutes, is_active, created_at, updated_at FROM doctor_schedules
WHERE doctor_id = $1 AND is_active = true
ORDER BY day_of_week, start_time
`

func (q *Queries) ListDoctorSchedules(ctx context.Context, doctorID uuid.UUID) ([]DoctorSchedule, error) {
	rows, err := q.db.Query(ctx, listDoctorSchedules, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoctorSchedule{}
	for rows.Next() {
		var i DoctorSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctors = `-- name: ListDoctors :many
SELECT d.id, d.user_id, d.specialization, d.license_number, d.bio, d.is_active, d.created_at, d.updated_at, u.full_name, u.email AS user_email FROM doctors d
JOIN users u ON u.id = d.user_id
WHERE ($3::boolean = false OR d.is_active = $3)
  AND $4::text = '' OR d.specialization ILIKE '%' || $4 || '%'
ORDER BY u.full_name
LIMIT $1 OFFSET $2
`

type ListDoctorsParams struct {
	Limit          int32
	Offset         int32
	IsActive       bool
	Specialization string
}

type ListDoctorsRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Specialization string
	LicenseNumber  string
	Bio            *string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	FullName       string
	UserEmail      string
}

func (q *Queries) ListDoctors(ctx context.Context, arg ListDoctorsParams) ([]ListDoctorsRow, error) {
	rows, err := q.db.Query(ctx, listDoctors,
		arg.Limit,
		arg.Offset,
		arg.IsActive,
		arg.Specialization,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoctorsRow{}
	for rows.Next() {
		var i ListDoctorsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Specialization,
			&i.LicenseNumber,
			&i.Bio,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleExceptions = `-- name: ListScheduleExceptions :many
SELECT id, doctor_id, exception_date, is_unavailable, start_time, end_time, reason, created_at, updated_at FROM doctor_schedule_exceptions
WHERE doctor_id = $1 AND exception_date BETWEEN $2 AND $3
ORDER BY exception_date
`

type ListScheduleExceptionsParams struct {
	DoctorID        uuid.UUID
	ExceptionDate   time.Time
	ExceptionDate_2 time.Time
}

func (q *Queries) ListScheduleExceptions(ctx context.Context, arg ListScheduleExceptionsParams) ([]DoctorScheduleException, error) {
	rows, err := q.db.Query(ctx, listScheduleExceptions, arg.DoctorID, arg.ExceptionDate, arg.ExceptionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoctorScheduleException{}
	for rows.Next() {
		var i DoctorScheduleException
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.ExceptionDate,
			&i.IsUnavailable,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
