// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID                 uuid.UUID   `json:"id"`
	PatientID          uuid.UUID   `json:"patient_id"`
	DoctorID           uuid.UUID   `json:"doctor_id"`
	ScheduleID         pgtype.UUID `json:"schedule_id"`
	StartTime          time.Time   `json:"start_time"`
	EndTime            time.Time   `json:"end_time"`
	Status             string      `json:"status"`
	Notes              pgtype.Text `json:"notes"`
	CancellationReason pgtype.Text `json:"cancellation_reason"`
	CreatedBy          pgtype.UUID `json:"created_by"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type Doctor struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Specialization pgtype.Text `json:"specialization"`
	LicenseNumber  pgtype.Text `json:"license_number"`
	Bio            pgtype.Text `json:"bio"`
	IsActive       bool        `json:"is_active"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type DoctorSchedule struct {
	ID        uuid.UUID   `json:"id"`
	DoctorID  uuid.UUID   `json:"doctor_id"`
	DayOfWeek int16       `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	IsActive  bool        `json:"is_active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type DoctorScheduleException struct {
	ID            uuid.UUID   `json:"id"`
	DoctorID      uuid.UUID   `json:"doctor_id"`
	ExceptionDate pgtype.Date `json:"exception_date"`
	StartTime     pgtype.Time `json:"start_time"`
	EndTime       pgtype.Time `json:"end_time"`
	IsUnavailable bool        `json:"is_unavailable"`
	Reason        pgtype.Text `json:"reason"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Patient struct {
	ID                    uuid.UUID   `json:"id"`
	UserID                uuid.UUID   `json:"user_id"`
	DateOfBirth           pgtype.Date `json:"date_of_birth"`
	Gender                pgtype.Text `json:"gender"`
	Address               pgtype.Text `json:"address"`
	EmergencyContactName  pgtype.Text `json:"emergency_contact_name"`
	EmergencyContactPhone pgtype.Text `json:"emergency_contact_phone"`
	MedicalNotes          pgtype.Text `json:"medical_notes"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
}

type User struct {
	ID            uuid.UUID   `json:"id"`
	Email         string      `json:"email"`
	PasswordHash  string      `json:"password_hash"`
	FullName      string      `json:"full_name"`
	Phone         pgtype.Text `json:"phone"`
	IsActive      bool        `json:"is_active"`
	EmailVerified bool        `json:"email_verified"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
