// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID                 uuid.UUID
	PatientID          uuid.UUID
	DoctorID           uuid.UUID
	StartTime          time.Time
	EndTime            time.Time
	Status             string
	Notes              *string
	CancellationReason *string
	Version            int32
	CreatedBy          *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type AuditLog struct {
	ID          uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Details     json.RawMessage
	CreatedAt   time.Time
}

type Doctor struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Specialization string
	LicenseNumber  string
	Bio            *string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type DoctorSchedule struct {
	ID          uuid.UUID
	DoctorID    uuid.UUID
	DayOfWeek   int16
	StartTime   pgtype.Time
	EndTime     pgtype.Time
	SlotMinutes int32
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DoctorScheduleException struct {
	ID            uuid.UUID
	DoctorID      uuid.UUID
	ExceptionDate time.Time
	IsUnavailable bool
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	Reason        *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type IdempotencyKey struct {
	Key            string
	Endpoint       string
	UserID         *uuid.UUID
	RequestHash    string
	ResponseStatus int32
	ResponseBody   *json.RawMessage
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

type Notification struct {
	ID            uuid.UUID
	AppointmentID *uuid.UUID
	Channel       string
	Recipient     string
	Subject       *string
	Body          string
	Status        string
	Attempts      int32
	LastError     *string
	NatsMsgID     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Patient struct {
	ID                    uuid.UUID
	UserID                *uuid.UUID
	FullName              string
	DateOfBirth           *time.Time
	Gender                *string
	Phone                 *string
	Address               *string
	EmergencyContactName  *string
	EmergencyContactPhone *string
	MedicalNotes          *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Role struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	FullName     string
	Phone        *string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserRole struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

type UserTenant struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TenantID  uuid.UUID
	RoleName  string
	IsActive  bool
	CreatedAt time.Time
}
