// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID                 uuid.UUID
	ProfileID          uuid.UUID
	DoctorProfileID    uuid.UUID
	AppointmentTypeID  uuid.UUID
	ScheduledStart     time.Time
	ScheduledEnd       time.Time
	Status             string
	VisitNotes         pgtype.Text
	FollowUpDate       *time.Time
	CancellationReason pgtype.Text
	Version            int32
	CreatedBy          *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type AppointmentType struct {
	ID              uuid.UUID
	Name            string
	DurationMinutes int32
	Price           pgtype.Numeric
	Color           *string
	Icon            *string
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type IdempotencyKey struct {
	Key            string
	Endpoint       string
	UserID         *uuid.UUID
	RequestHash    string
	ResponseStatus int32
	ResponseBody   *json.RawMessage
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

type Permission struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

type Profile struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProfileRole struct {
	ProfileID uuid.UUID
	RoleID    uuid.UUID
}

type QueueEntry struct {
	ID            uuid.UUID
	AppointmentID *uuid.UUID
	ProfileID     uuid.UUID
	Status        string
	Priority      int32
	CheckedInAt   time.Time
	CalledAt      *time.Time
	StartedAt     *time.Time
	CompletedAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TenantConfig struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Language     string
	Timezone     string
	OpeningHours json.RawMessage
	Settings     json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID           uuid.UUID
	Phone        string
	PasswordHash string
	FullName     string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsAdmin      bool
}

type UserRefreshToken struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	TokenHash      string
	ExpiresAt      time.Time
	Revoked        bool
	ReplacedByHash *string
	CreatedAt      time.Time
}
