// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
    user_id, date_of_birth, gender, address, emergency_contact_name, emergency_contact_phone, medical_notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, date_of_birth, gender, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at
`

type CreatePatientParams struct {
	UserID                uuid.UUID   `json:"user_id"`
	DateOfBirth           pgtype.Date `json:"date_of_birth"`
	Gender                pgtype.Text `json:"gender"`
	Address               pgtype.Text `json:"address"`
	EmergencyContactName  pgtype.Text `json:"emergency_contact_name"`
	EmergencyContactPhone pgtype.Text `json:"emergency_contact_phone"`
	MedicalNotes          pgtype.Text `json:"medical_notes"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.UserID,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalNotes,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients WHERE id = $1
`

func (q *Queries) DeletePatient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePatient, id)
	return err
}

const getPatient = `-- name: GetPatient :one
SELECT id, user_id, date_of_birth, gender, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at
FROM patients
WHERE id = $1
`

func (q *Queries) GetPatient(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatient, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByUserID = `-- name: GetPatientByUserID :one
SELECT id, user_id, date_of_birth, gender, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at
FROM patients
WHERE user_id = $1
`

func (q *Queries) GetPatientByUserID(ctx context.Context, userID uuid.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByUserID, userID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, user_id, date_of_birth, gender, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at
FROM patients
ORDER BY created_at DESC
`

func (q *Queries) ListPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DateOfBirth,
			&i.Gender,
			&i.Address,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET date_of_birth = $2, gender = $3, address = $4, emergency_contact_name = $5, emergency_contact_phone = $6, medical_notes = $7, updated_at = now()
WHERE id = $1
RETURNING id, user_id, date_of_birth, gender, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at
`

type UpdatePatientParams struct {
	ID                    uuid.UUID   `json:"id"`
	DateOfBirth           pgtype.Date `json:"date_of_birth"`
	Gender                pgtype.Text `json:"gender"`
	Address               pgtype.Text `json:"address"`
	EmergencyContactName  pgtype.Text `json:"emergency_contact_name"`
	EmergencyContactPhone pgtype.Text `json:"emergency_contact_phone"`
	MedicalNotes          pgtype.Text `json:"medical_notes"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.ID,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalNotes,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
