// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPatients = `-- name: CountPatients :one
SELECT count(*) FROM patients
WHERE $1::text = '' OR full_name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountPatients(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countPatients, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
    full_name, date_of_birth, gender, phone, address,
    emergency_contact_name, emergency_contact_phone, medical_notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, full_name, date_of_birth, gender, phone, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at
`

type CreatePatientParams struct {
	FullName              string
	DateOfBirth           *time.Time
	Gender                *string
	Phone                 *string
	Address               *string
	EmergencyContactName  *string
	EmergencyContactPhone *string
	MedicalNotes          *string
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Phone,
		arg.Address,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalNotes,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Phone,
		&i.Address,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatient = `-- name: DeletePatient :execrows
DELETE FROM patients WHERE id = $1
`

func (q *Queries) DeletePatient(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePatient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, user_id, full_name, date_of_birth, gender, phone, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at FROM patients WHERE id = $1
`

func (q *Queries) GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Phone,
		&i.Address,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientIDByUserID = `-- name: GetPatientIDByUserID :one
SELECT id FROM patients WHERE user_id = $1
`

func (q *Queries) GetPatientIDByUserID(ctx context.Context, userID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPatientIDByUserID, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const searchPatients = `-- name: SearchPatients :many
SELECT id, user_id, full_name, date_of_birth, gender, phone, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at FROM patients
WHERE $3::text = '' OR full_name ILIKE '%' || $3 || '%'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type SearchPatientsParams struct {
	Limit  int32
	Offset int32
	Search string
}

func (q *Queries) SearchPatients(ctx context.Context, arg SearchPatientsParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, searchPatients, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Phone,
			&i.Address,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients SET
    full_name = COALESCE($1, full_name),
    date_of_birth = COALESCE($2, date_of_birth),
    gender = COALESCE($3, gender),
    phone = COALESCE($4, phone),
    address = COALESCE($5, address),
    emergency_contact_name = COALESCE($6, emergency_contact_name),
    emergency_contact_phone = COALESCE($7, emergency_contact_phone),
    medical_notes = COALESCE($8, medical_notes)
WHERE id = $9
RETURNING id, user_id, full_name, date_of_birth, gender, phone, address, emergency_contact_name, emergency_contact_phone, medical_notes, created_at, updated_at
`

type UpdatePatientParams struct {
	FullName              *string
	DateOfBirth           *time.Time
	Gender                *string
	Phone                 *string
	Address               *string
	EmergencyContactName  *string
	EmergencyContactPhone *string
	MedicalNotes          *string
	ID                    uuid.UUID
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Phone,
		arg.Address,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.MedicalNotes,
		arg.ID,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Phone,
		&i.Address,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
