// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error)
	CountPatients(ctx context.Context, search string) (int64, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error)
	CreateDoctorSchedule(ctx context.Context, arg CreateDoctorScheduleParams) (DoctorSchedule, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreateScheduleException(ctx context.Context, arg CreateScheduleExceptionParams) (DoctorScheduleException, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateDoctorSchedule(ctx context.Context, id uuid.UUID) error
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	DeletePatient(ctx context.Context, id uuid.UUID) (int64, error)
	GetAppointmentByID(ctx context.Context, id uuid.UUID) (Appointment, error)
	GetDoctorByID(ctx context.Context, id uuid.UUID) (GetDoctorByIDRow, error)
	GetIdempotentResponse(ctx context.Context, arg GetIdempotentResponseParams) (GetIdempotentResponseRow, error)
	GetNotificationByMsgID(ctx context.Context, natsMsgID *string) (Notification, error)
	GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertIdempotentResponse(ctx context.Context, arg InsertIdempotentResponseParams) error
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	ListActiveAppointmentsForDoctorInRange(ctx context.Context, arg ListActiveAppointmentsForDoctorInRangeParams) ([]Appointment, error)
	ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error)
	ListDoctorSchedules(ctx context.Context, doctorID uuid.UUID) ([]DoctorSchedule, error)
	ListDoctors(ctx context.Context, arg ListDoctorsParams) ([]ListDoctorsRow, error)
	ListScheduleExceptions(ctx context.Context, arg ListScheduleExceptionsParams) ([]DoctorScheduleException, error)
	ListUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error)
	MarkNotificationDead(ctx context.Context, arg MarkNotificationDeadParams) error
	MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error
	MarkNotificationSent(ctx context.Context, id uuid.UUID) error
	RescheduleAppointment(ctx context.Context, arg RescheduleAppointmentParams) (Appointment, error)
	SearchPatients(ctx context.Context, arg SearchPatientsParams) ([]Patient, error)
	TransitionAppointmentStatus(ctx context.Context, arg TransitionAppointmentStatusParams) (Appointment, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
}

var _ Querier = (*Queries)(nil)
