// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Staff bindings ---
	AddUserTenant(ctx context.Context, arg AddUserTenantParams) (UserTenant, error)
	CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error)
	// Appointments (schema v2: profile-based, typed, queue-ready)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	// Tenants (global registry) — schema v2
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUserTenant(ctx context.Context, arg DeactivateUserTenantParams) error
	DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	GetAppointmentByID(ctx context.Context, id uuid.UUID) (Appointment, error)
	GetIdempotentResponse(ctx context.Context, arg GetIdempotentResponseParams) (IdempotencyKey, error)
	GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error)
	GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Auth (schema v2: phone-only identity)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	InsertIdempotentResponse(ctx context.Context, arg InsertIdempotentResponseParams) error
	ListAppointmentTypes(ctx context.Context) ([]AppointmentType, error)
	ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListTenantsForUser(ctx context.Context, userID uuid.UUID) ([]Tenant, error)
	ListUserRoles(ctx context.Context, profileID uuid.UUID) ([]Role, error)
	RescheduleAppointment(ctx context.Context, arg RescheduleAppointmentParams) (Appointment, error)
	SetTenantActive(ctx context.Context, arg SetTenantActiveParams) error
	TransitionAppointmentStatus(ctx context.Context, arg TransitionAppointmentStatusParams) (Appointment, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpsertPatientProfile(ctx context.Context, arg UpsertPatientProfileParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
