// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_profiles.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotentResponse = `-- name: GetIdempotentResponse :one
SELECT key, endpoint, user_id, request_hash, response_status, response_body, expires_at, created_at
FROM idempotency_keys WHERE key = $1 AND endpoint = $2
`

type GetIdempotentResponseParams struct {
	Key      string
	Endpoint string
}

func (q *Queries) GetIdempotentResponse(ctx context.Context, arg GetIdempotentResponseParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotentResponse, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Endpoint,
		&i.UserID,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, user_id, display_name, status, created_at, updated_at FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, display_name, status, created_at, updated_at FROM profiles WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIdempotentResponse = `-- name: InsertIdempotentResponse :exec
INSERT INTO idempotency_keys (key, endpoint, user_id, request_hash, response_status, response_body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertIdempotentResponseParams struct {
	Key            string
	Endpoint       string
	UserID         *uuid.UUID
	RequestHash    string
	ResponseStatus int32
	ResponseBody   *json.RawMessage
	ExpiresAt      time.Time
}

func (q *Queries) InsertIdempotentResponse(ctx context.Context, arg InsertIdempotentResponseParams) error {
	_, err := q.db.Exec(ctx, insertIdempotentResponse,
		arg.Key,
		arg.Endpoint,
		arg.UserID,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	return err
}

const listAppointmentTypes = `-- name: ListAppointmentTypes :many
SELECT id, name, duration_minutes, price, color, icon, is_active, created_at, updated_at FROM appointment_types WHERE is_active = true ORDER BY name
`

func (q *Queries) ListAppointmentTypes(ctx context.Context) ([]AppointmentType, error) {
	rows, err := q.db.Query(ctx, listAppointmentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppointmentType{}
	for rows.Next() {
		var i AppointmentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMinutes,
			&i.Price,
			&i.Color,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.name
FROM roles r
JOIN profile_roles pr ON pr.role_id = r.id
WHERE pr.profile_id = $1
`

func (q *Queries) ListUserRoles(ctx context.Context, profileID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPatientProfile = `-- name: UpsertPatientProfile :one
INSERT INTO profiles (user_id, display_name)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
    display_name = COALESCE(EXCLUDED.display_name, profiles.display_name),
    updated_at = now()
RETURNING id, user_id, display_name, status, created_at, updated_at
`

type UpsertPatientProfileParams struct {
	UserID      uuid.UUID
	DisplayName string
}

func (q *Queries) UpsertPatientProfile(ctx context.Context, arg UpsertPatientProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertPatientProfile, arg.UserID, arg.DisplayName)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
