// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_profiles.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToProfile = `-- name: AssignRoleToProfile :exec
INSERT INTO profile_roles (profile_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToProfileParams struct {
	ProfileID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) AssignRoleToProfile(ctx context.Context, arg AssignRoleToProfileParams) error {
	_, err := q.db.Exec(ctx, assignRoleToProfile, arg.ProfileID, arg.RoleID)
	return err
}

const countProfilesByRole = `-- name: CountProfilesByRole :one
SELECT COUNT(*)
FROM profiles p
JOIN profile_roles pr ON pr.profile_id = p.id
JOIN roles r ON r.id = pr.role_id AND r.name = $1
WHERE p.status = 'active'
`

func (q *Queries) CountProfilesByRole(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countProfilesByRole, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointmentType = `-- name: CreateAppointmentType :one
INSERT INTO appointment_types (name, duration_minutes, price, color, icon)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, duration_minutes, price, color, icon, is_active, created_at, updated_at
`

type CreateAppointmentTypeParams struct {
	Name            string
	DurationMinutes int32
	Price           pgtype.Numeric
	Color           *string
	Icon            *string
}

func (q *Queries) CreateAppointmentType(ctx context.Context, arg CreateAppointmentTypeParams) (AppointmentType, error) {
	row := q.db.QueryRow(ctx, createAppointmentType,
		arg.Name,
		arg.DurationMinutes,
		arg.Price,
		arg.Color,
		arg.Icon,
	)
	var i AppointmentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationMinutes,
		&i.Price,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING id, user_id, display_name, status, created_at, updated_at
`

type CreateProfileParams struct {
	UserID      uuid.UUID
	DisplayName string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.DisplayName)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduleException = `-- name: CreateScheduleException :one
INSERT INTO schedule_exceptions (doctor_profile_id, date, start_time, end_time, type, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, doctor_profile_id, date, start_time, end_time, type, reason, created_at, updated_at
`

type CreateScheduleExceptionParams struct {
	DoctorProfileID uuid.UUID
	Date            time.Time
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	Type            string
	Reason          pgtype.Text
}

func (q *Queries) CreateScheduleException(ctx context.Context, arg CreateScheduleExceptionParams) (ScheduleException, error) {
	row := q.db.QueryRow(ctx, createScheduleException,
		arg.DoctorProfileID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.Type,
		arg.Reason,
	)
	var i ScheduleException
	err := row.Scan(
		&i.ID,
		&i.DoctorProfileID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Type,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDoctorSchedules = `-- name: DeleteDoctorSchedules :exec
DELETE FROM doctor_schedules WHERE doctor_profile_id = $1
`

// Removes every weekly window for a doctor, so a PUT can replace the set.
func (q *Queries) DeleteDoctorSchedules(ctx context.Context, doctorProfileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDoctorSchedules, doctorProfileID)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleException = `-- name: DeleteScheduleException :exec
DELETE FROM schedule_exceptions WHERE id = $1
`

func (q *Queries) DeleteScheduleException(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleException, id)
	return err
}

const getAppointmentTypeByID = `-- name: GetAppointmentTypeByID :one
SELECT id, name, duration_minutes, price, color, icon, is_active, created_at, updated_at FROM appointment_types WHERE id = $1
`

func (q *Queries) GetAppointmentTypeByID(ctx context.Context, id uuid.UUID) (AppointmentType, error) {
	row := q.db.QueryRow(ctx, getAppointmentTypeByID, id)
	var i AppointmentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationMinutes,
		&i.Price,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotentResponse = `-- name: GetIdempotentResponse :one
SELECT key, endpoint, user_id, request_hash, response_status, response_body, expires_at, created_at
FROM idempotency_keys WHERE key = $1 AND endpoint = $2
`

type GetIdempotentResponseParams struct {
	Key      string
	Endpoint string
}

func (q *Queries) GetIdempotentResponse(ctx context.Context, arg GetIdempotentResponseParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotentResponse, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Endpoint,
		&i.UserID,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, user_id, display_name, status, created_at, updated_at FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, display_name, status, created_at, updated_at FROM profiles WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const insertDoctorSchedule = `-- name: InsertDoctorSchedule :one
INSERT INTO doctor_schedules (doctor_profile_id, day_of_week, start_time, end_time, slot_duration, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, doctor_profile_id, day_of_week, start_time, end_time, slot_duration, is_active, created_at, updated_at
`

type InsertDoctorScheduleParams struct {
	DoctorProfileID uuid.UUID
	DayOfWeek       int16
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	SlotDuration    int32
	IsActive        bool
}

func (q *Queries) InsertDoctorSchedule(ctx context.Context, arg InsertDoctorScheduleParams) (DoctorSchedule, error) {
	row := q.db.QueryRow(ctx, insertDoctorSchedule,
		arg.DoctorProfileID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.SlotDuration,
		arg.IsActive,
	)
	var i DoctorSchedule
	err := row.Scan(
		&i.ID,
		&i.DoctorProfileID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.SlotDuration,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIdempotentResponse = `-- name: InsertIdempotentResponse :exec
INSERT INTO idempotency_keys (key, endpoint, user_id, request_hash, response_status, response_body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertIdempotentResponseParams struct {
	Key            string
	Endpoint       string
	UserID         *uuid.UUID
	RequestHash    string
	ResponseStatus int32
	ResponseBody   *json.RawMessage
	ExpiresAt      time.Time
}

func (q *Queries) InsertIdempotentResponse(ctx context.Context, arg InsertIdempotentResponseParams) error {
	_, err := q.db.Exec(ctx, insertIdempotentResponse,
		arg.Key,
		arg.Endpoint,
		arg.UserID,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	return err
}

const listAppointmentTypes = `-- name: ListAppointmentTypes :many
SELECT id, name, duration_minutes, price, color, icon, is_active, created_at, updated_at FROM appointment_types WHERE is_active = true ORDER BY name
`

func (q *Queries) ListAppointmentTypes(ctx context.Context) ([]AppointmentType, error) {
	rows, err := q.db.Query(ctx, listAppointmentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppointmentType{}
	for rows.Next() {
		var i AppointmentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMinutes,
			&i.Price,
			&i.Color,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctorSchedules = `-- name: ListDoctorSchedules :many
SELECT id, doctor_profile_id, day_of_week, start_time, end_time, slot_duration, is_active, created_at, updated_at
FROM doctor_schedules
WHERE doctor_profile_id = $1
ORDER BY day_of_week, start_time
`

// Every weekly window for a doctor, active or not, newest-edited last.
func (q *Queries) ListDoctorSchedules(ctx context.Context, doctorProfileID uuid.UUID) ([]DoctorSchedule, error) {
	rows, err := q.db.Query(ctx, listDoctorSchedules, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoctorSchedule{}
	for rows.Next() {
		var i DoctorSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DoctorProfileID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotDuration,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctorSchedulesOnDay = `-- name: ListDoctorSchedulesOnDay :many
SELECT s.id, s.doctor_profile_id, s.day_of_week, s.start_time, s.end_time,
    s.is_active, s.created_at, s.updated_at
FROM doctor_schedules s
WHERE s.doctor_profile_id = $1
  AND s.is_active = true
  AND s.day_of_week = EXTRACT(DOW FROM $2::timestamptz)::int
  AND EXISTS (SELECT 1 FROM profiles p WHERE p.id = s.doctor_profile_id AND p.status = 'active')
ORDER BY s.start_time
`

type ListDoctorSchedulesOnDayParams struct {
	DoctorProfileID uuid.UUID
	Date            time.Time
}

type ListDoctorSchedulesOnDayRow struct {
	ID              uuid.UUID
	DoctorProfileID uuid.UUID
	DayOfWeek       int16
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Active schedule windows for an active doctor on a given week day (0 = Sunday).
func (q *Queries) ListDoctorSchedulesOnDay(ctx context.Context, arg ListDoctorSchedulesOnDayParams) ([]ListDoctorSchedulesOnDayRow, error) {
	rows, err := q.db.Query(ctx, listDoctorSchedulesOnDay, arg.DoctorProfileID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoctorSchedulesOnDayRow{}
	for rows.Next() {
		var i ListDoctorSchedulesOnDayRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorProfileID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT
    p.id,
    p.user_id,
    p.display_name,
    p.status,
    p.created_at,
    p.updated_at,
    COALESCE(array_agg(r.name ORDER BY r.name) FILTER (WHERE r.name IS NOT NULL), ARRAY[]::varchar[])::text[] AS role_names
FROM profiles p
LEFT JOIN profile_roles pr ON pr.profile_id = p.id
LEFT JOIN roles r ON r.id = pr.role_id
GROUP BY p.id
ORDER BY p.display_name
`

type ListProfilesRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RoleNames   []string
}

func (q *Queries) ListProfiles(ctx context.Context) ([]ListProfilesRow, error) {
	rows, err := q.db.Query(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilesRow{}
	for rows.Next() {
		var i ListProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByRole = `-- name: ListProfilesByRole :many
SELECT
    p.id,
    p.user_id,
    p.display_name,
    p.status,
    p.created_at,
    p.updated_at
FROM profiles p
JOIN profile_roles pr ON pr.profile_id = p.id
JOIN roles r ON r.id = pr.role_id AND r.name = $1
ORDER BY p.display_name
`

func (q *Queries) ListProfilesByRole(ctx context.Context, name string) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfilesByRole, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByRolePaginated = `-- name: ListProfilesByRolePaginated :many
SELECT
    p.id,
    p.user_id,
    p.display_name,
    p.status,
    p.created_at,
    p.updated_at
FROM profiles p
JOIN profile_roles pr ON pr.profile_id = p.id
JOIN roles r ON r.id = pr.role_id AND r.name = $1
WHERE p.status = 'active'
ORDER BY p.display_name
LIMIT $2 OFFSET $3
`

type ListProfilesByRolePaginatedParams struct {
	Name   string
	Limit  int32
	Offset int32
}

func (q *Queries) ListProfilesByRolePaginated(ctx context.Context, arg ListProfilesByRolePaginatedParams) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfilesByRolePaginated, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleExceptions = `-- name: ListScheduleExceptions :many
SELECT id, doctor_profile_id, date, start_time, end_time, type, reason, created_at, updated_at
FROM schedule_exceptions
WHERE doctor_profile_id = $1
ORDER BY date, start_time
`

func (q *Queries) ListScheduleExceptions(ctx context.Context, doctorProfileID uuid.UUID) ([]ScheduleException, error) {
	rows, err := q.db.Query(ctx, listScheduleExceptions, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleException{}
	for rows.Next() {
		var i ScheduleException
		if err := rows.Scan(
			&i.ID,
			&i.DoctorProfileID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Type,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleExceptionsForDate = `-- name: ListScheduleExceptionsForDate :many
SELECT id, doctor_profile_id, date, start_time, end_time, type, reason, created_at, updated_at
FROM schedule_exceptions
WHERE doctor_profile_id = $1 AND date = $2
ORDER BY start_time
`

type ListScheduleExceptionsForDateParams struct {
	DoctorProfileID uuid.UUID
	Date            time.Time
}

func (q *Queries) ListScheduleExceptionsForDate(ctx context.Context, arg ListScheduleExceptionsForDateParams) ([]ScheduleException, error) {
	rows, err := q.db.Query(ctx, listScheduleExceptionsForDate, arg.DoctorProfileID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleException{}
	for rows.Next() {
		var i ScheduleException
		if err := rows.Scan(
			&i.ID,
			&i.DoctorProfileID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Type,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.name
FROM roles r
JOIN profile_roles pr ON pr.role_id = r.id
WHERE pr.profile_id = $1
`

type ListUserRolesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListUserRoles(ctx context.Context, profileID uuid.UUID) ([]ListUserRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserRoles, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRolesRow{}
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileHasRole = `-- name: ProfileHasRole :one
SELECT EXISTS (
    SELECT 1
    FROM profile_roles pr
    JOIN roles r ON r.id = pr.role_id
    WHERE pr.profile_id = $1 AND r.name = $2
)
`

type ProfileHasRoleParams struct {
	ProfileID uuid.UUID
	Name      string
}

func (q *Queries) ProfileHasRole(ctx context.Context, arg ProfileHasRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, profileHasRole, arg.ProfileID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateAppointmentType = `-- name: UpdateAppointmentType :one
UPDATE appointment_types
SET name = $2,
    duration_minutes = $3,
    price = $4,
    color = $5,
    icon = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, duration_minutes, price, color, icon, is_active, created_at, updated_at
`

type UpdateAppointmentTypeParams struct {
	ID              uuid.UUID
	Name            string
	DurationMinutes int32
	Price           pgtype.Numeric
	Color           *string
	Icon            *string
}

func (q *Queries) UpdateAppointmentType(ctx context.Context, arg UpdateAppointmentTypeParams) (AppointmentType, error) {
	row := q.db.QueryRow(ctx, updateAppointmentType,
		arg.ID,
		arg.Name,
		arg.DurationMinutes,
		arg.Price,
		arg.Color,
		arg.Icon,
	)
	var i AppointmentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationMinutes,
		&i.Price,
		&i.Color,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPatientProfile = `-- name: UpsertPatientProfile :one
INSERT INTO profiles (user_id, display_name)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
    display_name = COALESCE(EXCLUDED.display_name, profiles.display_name),
    updated_at = now()
RETURNING id, user_id, display_name, status, created_at, updated_at
`

type UpsertPatientProfileParams struct {
	UserID      uuid.UUID
	DisplayName string
}

func (q *Queries) UpsertPatientProfile(ctx context.Context, arg UpsertPatientProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertPatientProfile, arg.UserID, arg.DisplayName)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
