// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, status, created_at, updated_at
`

type CreateTenantParams struct {
	Name string
	Slug string
}

// Tenants (global registry) — schema v2
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureUserTenantMembership = `-- name: EnsureUserTenantMembership :exec
INSERT INTO user_tenants (user_id, tenant_id)
VALUES ($1, $2)
ON CONFLICT (user_id, tenant_id) DO NOTHING
`

type EnsureUserTenantMembershipParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) EnsureUserTenantMembership(ctx context.Context, arg EnsureUserTenantMembershipParams) error {
	_, err := q.db.Exec(ctx, ensureUserTenantMembership, arg.UserID, arg.TenantID)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, status, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, status, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, status, created_at, updated_at FROM tenants WHERE status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTenantIDs = `-- name: ListUserTenantIDs :many
SELECT tenant_id FROM user_tenants WHERE user_id = $1
`

func (q *Queries) ListUserTenantIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserTenantIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var tenant_id uuid.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantActive = `-- name: SetTenantActive :exec
UPDATE tenants SET status = CASE WHEN $2 THEN 'active' ELSE 'inactive' END WHERE id = $1
`

type SetTenantActiveParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetTenantActive(ctx context.Context, arg SetTenantActiveParams) error {
	_, err := q.db.Exec(ctx, setTenantActive, arg.ID, arg.Status)
	return err
}
