// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addUserTenant = `-- name: AddUserTenant :one
INSERT INTO user_tenants (user_id, tenant_id)
VALUES ($1, $2)
ON CONFLICT (user_id, tenant_id) DO NOTHING
RETURNING id, user_id, tenant_id, is_active, created_at
`

type AddUserTenantParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

// Staff/doctor binding so the clinic appears in the user's tenant list.
func (q *Queries) AddUserTenant(ctx context.Context, arg AddUserTenantParams) (UserTenant, error) {
	row := q.db.QueryRow(ctx, addUserTenant, arg.UserID, arg.TenantID)
	var i UserTenant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, is_active, created_at, updated_at
`

type CreateTenantParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileForTenant = `-- name: GetProfileForTenant :one

SELECT user_id, role, is_active FROM profiles WHERE user_id = $1
`

type GetProfileForTenantRow struct {
	UserID   uuid.UUID
	Role     string
	IsActive bool
}

// GetProfileForTenant / UpsertPatientProfile live in profile.sql and run
// with search_path pinned to the active tenant schema.
func (q *Queries) GetProfileForTenant(ctx context.Context, userID uuid.UUID) (GetProfileForTenantRow, error) {
	row := q.db.QueryRow(ctx, getProfileForTenant, userID)
	var i GetProfileForTenantRow
	err := row.Scan(&i.UserID, &i.Role, &i.IsActive)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, is_active, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, is_active, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, is_active, created_at, updated_at FROM tenants WHERE is_active = true ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForUser = `-- name: ListTenantsForUser :many
SELECT t.id, t.name, t.slug, t.is_active, t.created_at, t.updated_at FROM tenants t
JOIN user_tenants ut ON ut.tenant_id = t.id
WHERE ut.user_id = $1 AND ut.is_active = true AND t.is_active = true
`

// Clinics where the user holds a staff/doctor binding. Patients browse all
// active tenants and need no binding to act inside one.
func (q *Queries) ListTenantsForUser(ctx context.Context, userID uuid.UUID) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantActive = `-- name: SetTenantActive :exec
UPDATE tenants SET is_active = $2 WHERE id = $1
`

type SetTenantActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetTenantActive(ctx context.Context, arg SetTenantActiveParams) error {
	_, err := q.db.Exec(ctx, setTenantActive, arg.ID, arg.IsActive)
	return err
}

const upsertPatientProfile = `-- name: UpsertPatientProfile :one
INSERT INTO profiles (user_id, role)
VALUES ($1, 'patient')
ON CONFLICT (user_id) DO UPDATE SET is_active = true
RETURNING user_id, role, is_active
`

type UpsertPatientProfileRow struct {
	UserID   uuid.UUID
	Role     string
	IsActive bool
}

func (q *Queries) UpsertPatientProfile(ctx context.Context, userID uuid.UUID) (UpsertPatientProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertPatientProfile, userID)
	var i UpsertPatientProfileRow
	err := row.Scan(&i.UserID, &i.Role, &i.IsActive)
	return i, err
}
