// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTenantMember = `-- name: AddTenantMember :one
INSERT INTO user_tenants (user_id, tenant_id, role_name)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, tenant_id) DO UPDATE
  SET role_name = EXCLUDED.role_name, is_active = true
RETURNING id, user_id, tenant_id, role_name, is_active, created_at
`

type AddTenantMemberParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	RoleName string
}

func (q *Queries) AddTenantMember(ctx context.Context, arg AddTenantMemberParams) (UserTenant, error) {
	row := q.db.QueryRow(ctx, addTenantMember, arg.UserID, arg.TenantID, arg.RoleName)
	var i UserTenant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, is_active, created_at, updated_at
`

type CreateTenantParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT ut.user_id, ut.tenant_id, ut.role_name, ut.is_active,
       t.slug AS tenant_slug, t.name AS tenant_name
FROM user_tenants ut
JOIN tenants t ON t.id = ut.tenant_id
WHERE ut.user_id = $1 AND ut.tenant_id = $2 AND ut.is_active = true
`

type GetMembershipParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

type GetMembershipRow struct {
	UserID     uuid.UUID
	TenantID   uuid.UUID
	RoleName   string
	IsActive   bool
	TenantSlug string
	TenantName string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.TenantID)
	var i GetMembershipRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.RoleName,
		&i.IsActive,
		&i.TenantSlug,
		&i.TenantName,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, is_active, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, is_active, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT ut.user_id, ut.tenant_id, ut.role_name, ut.is_active,
       t.slug AS tenant_slug, t.name AS tenant_name
FROM user_tenants ut
JOIN tenants t ON t.id = ut.tenant_id
WHERE ut.user_id = $1 AND ut.is_active = true AND t.is_active = true
`

type ListMembershipsForUserRow struct {
	UserID     uuid.UUID
	TenantID   uuid.UUID
	RoleName   string
	IsActive   bool
	TenantSlug string
	TenantName string
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.TenantID,
			&i.RoleName,
			&i.IsActive,
			&i.TenantSlug,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, is_active, created_at, updated_at FROM tenants ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantActive = `-- name: SetTenantActive :exec
UPDATE tenants SET is_active = $2 WHERE id = $1
`

type SetTenantActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetTenantActive(ctx context.Context, arg SetTenantActiveParams) error {
	_, err := q.db.Exec(ctx, setTenantActive, arg.ID, arg.IsActive)
	return err
}
