// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, password_hash, full_name)
VALUES ($1, $2, $3)
RETURNING id, phone, password_hash, full_name, status, created_at, updated_at, is_admin
`

type CreateUserParams struct {
	Phone        string
	PasswordHash string
	FullName     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Phone, arg.PasswordHash, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM user_refresh_tokens
WHERE user_id = $1 AND token_hash = $2
`

type DeleteRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, arg.UserID, arg.TokenHash)
	return err
}

const getUserAdminFlag = `-- name: GetUserAdminFlag :one
SELECT is_admin FROM users WHERE id = $1
`

func (q *Queries) GetUserAdminFlag(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getUserAdminFlag, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, password_hash, full_name, status, created_at, updated_at, is_admin FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one

SELECT id, phone, password_hash, full_name, status, created_at, updated_at, is_admin FROM users WHERE phone = $1
`

// Auth (schema v2: phone-only identity)
func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec

INSERT INTO user_refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET
    token_hash = EXCLUDED.token_hash,
    expires_at = EXCLUDED.expires_at,
    revoked = false
`

type InsertRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

// Refresh tokens (hashed storage for validation/revocation)
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2 WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}

const validateRefreshToken = `-- name: ValidateRefreshToken :one
SELECT expires_at FROM user_refresh_tokens
WHERE user_id = $1 AND token_hash = $2 AND revoked = false AND expires_at > now()
`

type ValidateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) ValidateRefreshToken(ctx context.Context, arg ValidateRefreshTokenParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, validateRefreshToken, arg.UserID, arg.TokenHash)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}
