package server

import (
	"os"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	apptapi "github.com/PandaX185/clinic-management/internal/appointment/api"
	authapi "github.com/PandaX185/clinic-management/internal/auth/api"
	authsvc "github.com/PandaX185/clinic-management/internal/auth/service"
	directoryapi "github.com/PandaX185/clinic-management/internal/directory/api"
	tenantapi "github.com/PandaX185/clinic-management/internal/tenant/api"
	tenantsvc "github.com/PandaX185/clinic-management/internal/tenant/service"

	"github.com/PandaX185/clinic-management/internal/platform/config"
	"github.com/PandaX185/clinic-management/internal/platform/metrics"
)

type RouterDeps struct {
	Cfg             config.Config
	RDB             *redis.Client
	Logger          Logger
	AuthH           *authapi.Handler
	AuthSvc         *authsvc.Service
	AppointH        *apptapi.Handler
	TenantH         *tenantapi.Handler
	TenantSvc       *tenantsvc.Service
	ProfileResolver ProfileResolver
	DirectoryH      *directoryapi.Handler
	Metrics         *metrics.Metrics
}

func NewRouter(deps RouterDeps) *gin.Engine {
	if deps.Cfg.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}
	r := gin.New()
	// Never trust client-supplied X-Forwarded-For: only the direct peer is
	// a valid ClientIP source unless an explicit proxy list is configured
	// (SEC-05). Behind a reverse proxy, set GIN_TRUSTED_PROXIES.
	if trusted := os.Getenv("GIN_TRUSTED_PROXIES"); trusted != "" {
		_ = r.SetTrustedProxies(strings.Split(trusted, ","))
	} else {
		_ = r.SetTrustedProxies(nil)
	}

	r.Use(gin.Recovery())
	r.Use(RequestID())
	if deps.Metrics != nil {
		r.Use(MetricsMiddleware(deps.Metrics))
	}
	// ErrorHandler must run BEFORE route middleware so it can convert
	// aborts (c.Error + c.Abort) from e.g. TenantMiddleware into responses.
	r.Use(ErrorHandler(deps.Logger))
	r.Use(RateLimit(deps.RDB, deps.Cfg.RateLimitPerMinute))
	r.Use(SecurityHeaders())
	r.Use(BodyLimit(maxBodyBytes))

	// Instrumentation: /metrics is served by the same gin engine so the app
	// exposes a single HTTP server.
	if deps.Metrics != nil {
		r.GET("/metrics", gin.WrapH(deps.Metrics.Handler()))
	}

	// Swagger UI + OpenAPI spec (docs generated by `make swagger`).
	// The UI lives at /swagger/index.html; the machine-readable spec at
	// /swagger/doc.json.
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	apiV1 := r.Group("/api/v1")

	deps.AuthH.RegisterRoutes(apiV1)

	// Global (auth-only) routes: authenticated identity but no X-Tenant-ID.
	global := apiV1.Group("")
	global.Use(authapi.JwtMiddleware(deps.AuthSvc))

	// Global super-admin only: provisioning clinics has no tenant context to
	// resolve an admin role from, so it is gated on the global users.is_admin
	// flag rather than a per-clinic role.
	globalAdmin := global.Group("")
	globalAdmin.Use(authapi.RequireGlobalAdmin(deps.AuthSvc))
	globalAdmin.POST("/tenants", deps.TenantH.Create)

	// Tenant-scoped routes: X-Tenant-ID required; role resolved per clinic.
	protected := apiV1.Group("")
	protected.Use(authapi.JwtMiddleware(deps.AuthSvc))
	protected.Use(TenantMiddleware(deps.TenantSvc, deps.ProfileResolver))

	// Per-clinic admin: resolved against the active tenant's roles.
	admin := protected.Group("")
	admin.Use(authapi.RequireRoles("admin"))
	admin.POST("/tenants/:id/staff", deps.TenantH.BindStaff)

	deps.TenantH.RegisterRoutes(global) // GET /tenants, /tenants/mine — browse clinics
	authProtected := global.Group("/auth")
	deps.AuthH.RegisterProtectedRoutes(authProtected) // GET /auth/me, /auth/tenants

	deps.DirectoryH.RegisterRoutes(protected) // profiles, doctors, appointment types

	deps.AppointH.RegisterRoutes(protected)

	return r
}
