package server

import (
	"os"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	bookingapi "github.com/PandaX185/clinic-management/internal/booking/api"
	catapi "github.com/PandaX185/clinic-management/internal/catalog/api"
	clinicapi "github.com/PandaX185/clinic-management/internal/clinic/api"
	clinicsvc "github.com/PandaX185/clinic-management/internal/clinic/service"
	idapi "github.com/PandaX185/clinic-management/internal/identity/api"
	idsvc "github.com/PandaX185/clinic-management/internal/identity/service"
	portalapi "github.com/PandaX185/clinic-management/internal/portal/api"
	queueapi "github.com/PandaX185/clinic-management/internal/queue/api"
	schedapi "github.com/PandaX185/clinic-management/internal/scheduling/api"

	"github.com/PandaX185/clinic-management/internal/platform/config"
	"github.com/PandaX185/clinic-management/internal/platform/metrics"
)

type RouterDeps struct {
	Cfg             config.Config
	RDB             *redis.Client
	Logger          Logger
	AuthH           *idapi.Handler
	AuthSvc         *idsvc.Service
	AppointH        *schedapi.Handler
	ClinicH         *clinicapi.Handler
	ClinicSvc       *clinicsvc.Service
	ProfileResolver ProfileResolver
	DirectoryH      *catapi.Handler
	PublicH         *bookingapi.Handler
	PatientH        *portalapi.Handler
	QueueH          *queueapi.Handler
	Metrics         *metrics.Metrics
}

func NewRouter(deps RouterDeps) *gin.Engine {
	if deps.Cfg.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}
	r := gin.New()
	// Never trust client-supplied X-Forwarded-For: only the direct peer is
	// a valid ClientIP source unless an explicit proxy list is configured
	// (SEC-05). Behind a reverse proxy, set GIN_TRUSTED_PROXIES.
	if trusted := os.Getenv("GIN_TRUSTED_PROXIES"); trusted != "" {
		_ = r.SetTrustedProxies(strings.Split(trusted, ","))
	} else {
		_ = r.SetTrustedProxies(nil)
	}

	r.Use(gin.Recovery())
	r.Use(RequestID())
	if deps.Metrics != nil {
		r.Use(MetricsMiddleware(deps.Metrics))
	}
	// ErrorHandler must run BEFORE route middleware so it can convert
	// aborts (c.Error + c.Abort) from e.g. TenantMiddleware into responses.
	r.Use(ErrorHandler(deps.Logger))
	r.Use(RateLimit(deps.RDB, deps.Cfg.RateLimitPerMinute))
	r.Use(SecurityHeaders())
	r.Use(BodyLimit(maxBodyBytes))

	// Instrumentation: /metrics is served by the same gin engine so the app
	// exposes a single HTTP server.
	if deps.Metrics != nil {
		r.GET("/metrics", gin.WrapH(deps.Metrics.Handler()))
	}

	// Swagger UI + OpenAPI spec (docs generated by `make swagger`).
	// The UI lives at /swagger/index.html; the machine-readable spec at
	// /swagger/doc.json.
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	apiV1 := r.Group("/api/v1")

	deps.AuthH.RegisterRoutes(apiV1)

	// Public clinic discovery: unauthenticated, no tenant context. This is
	// the surface patients reach before authenticating.
	deps.PublicH.RegisterRoutes(apiV1.Group("/booking"))

	// Global (auth-only) routes: authenticated identity but no X-Tenant-ID.
	global := apiV1.Group("")
	global.Use(idapi.JwtMiddleware(deps.AuthSvc))

	// Global super-admin only: provisioning clinics has no tenant context to
	// resolve an admin role from, so it is gated on the global users.is_admin
	// flag rather than a per-clinic role.
	globalAdmin := global.Group("")
	globalAdmin.Use(idapi.RequireGlobalAdmin(deps.AuthSvc))
	globalAdmin.POST("/clinics", deps.ClinicH.Create)

	// Tenant-scoped routes: X-Tenant-ID required; role resolved per clinic.
	protected := apiV1.Group("")
	protected.Use(idapi.JwtMiddleware(deps.AuthSvc))
	protected.Use(TenantMiddleware(deps.ClinicSvc, deps.ProfileResolver))

	// Per-clinic admin: resolved against the active tenant's roles.
	admin := protected.Group("")
	admin.Use(idapi.RequireRoles("admin"))
	admin.POST("/clinics/:id/staff", deps.ClinicH.BindStaff)

	deps.ClinicH.RegisterRoutes(global) // GET /clinics, /clinics/mine — browse clinics
	authProtected := global.Group("/auth")
	deps.AuthH.RegisterProtectedRoutes(authProtected) // GET /auth/me, /auth/clinics

	// Patient portal: JWT-only, operations span clinics so no X-Tenant-ID.
	deps.PatientH.RegisterRoutes(global)

	deps.DirectoryH.RegisterRoutes(protected) // profiles, doctors, appointment types

	deps.QueueH.RegisterRoutes(protected) // clinic queue / line management

	deps.AppointH.RegisterRoutes(protected)

	return r
}
